from django.core.management.base import BaseCommand

from public_content.models import SuccessStory


STORIES = [
    {
        "student_name": "Ravi Kumar",
        "slug": "ravi-banking-to-full-stack",
        "headline": "From banking operations to full-stack developer",
        "hook": "Ravi used live projects and mentor reviews to turn a career reset into a product role.",
        "track": "Full Stack",
        "background": "Career switcher",
        "outcome_type": "Career switch",
        "program_label": "Full Stack Advanced",
        "before_title": "Banking operations associate",
        "after_title": "Full-stack developer",
        "company_name": "Hyderabad SaaS startup",
        "salary_before_lpa": "4.60",
        "salary_after_lpa": "7.50",
        "salary_jump_percent": 63,
        "time_to_hire_months": 6,
        "quote": "The projects stopped me from feeling like I only knew tutorials. I could finally explain what I had built and why.",
        "advice": "Build fewer projects, but understand every decision inside them. Mentor feedback becomes valuable only when you return with a better second version.",
        "is_featured": True,
        "display_order": 1,
    },
    {
        "student_name": "Ananya Prasad",
        "slug": "ananya-teaching-to-data-analytics",
        "headline": "From classroom teaching to data analyst",
        "hook": "A portfolio of SQL investigations and dashboards helped Ananya make her experience legible to hiring teams.",
        "track": "Data Science",
        "background": "Career switcher",
        "outcome_type": "Career switch",
        "program_label": "Data Analytics Track",
        "before_title": "Mathematics teacher",
        "after_title": "Data analyst",
        "company_name": "Fintech team",
        "salary_before_lpa": "4.00",
        "salary_after_lpa": "6.20",
        "salary_jump_percent": 55,
        "time_to_hire_months": 5,
        "quote": "My teaching background was not a weakness once I learned to connect it to analysis, communication, and stakeholder questions.",
        "advice": "Do not hide your old career. Translate it. The domain knowledge and communication habits you already have can make your technical work stronger.",
        "is_featured": False,
        "display_order": 2,
    },
    {
        "student_name": "Siddharth K.",
        "slug": "siddharth-support-to-devops",
        "headline": "From technical support to DevOps engineer",
        "hook": "Siddharth converted troubleshooting experience into evidence through cloud labs and delivery automation.",
        "track": "Cloud & DevOps",
        "background": "Working professional",
        "outcome_type": "New role",
        "program_label": "Cloud & DevOps Track",
        "before_title": "Technical support engineer",
        "after_title": "DevOps engineer",
        "company_name": "Cloud services company",
        "salary_before_lpa": "5.20",
        "salary_after_lpa": "8.20",
        "salary_jump_percent": 58,
        "time_to_hire_months": 7,
        "quote": "The incident simulation gave me stories to tell in interviews, not just tool names to list.",
        "advice": "Treat every failed deployment as material. Write down the symptom, diagnosis, and fix; that habit improves both engineering and interviews.",
        "is_featured": False,
        "display_order": 3,
    },
    {
        "student_name": "Neha V.",
        "slug": "neha-commerce-to-business-intelligence",
        "headline": "From commerce graduate to BI analyst",
        "hook": "Neha combined business context with dashboard craft to land her first analytics role.",
        "track": "Data Science",
        "background": "Fresher",
        "outcome_type": "First job",
        "program_label": "Data Analytics Track",
        "before_title": "Commerce graduate",
        "after_title": "Business intelligence analyst",
        "company_name": "Retail analytics company",
        "salary_before_lpa": None,
        "salary_after_lpa": "5.40",
        "salary_jump_percent": 0,
        "time_to_hire_months": 4,
        "quote": "The capstone gave me a way to discuss business decisions instead of only describing charts.",
        "advice": "Choose projects where you can explain the decision behind every metric. A dashboard without a question is just decoration.",
        "is_featured": False,
        "display_order": 4,
    },
    {
        "student_name": "Mohammed R.",
        "slug": "mohammed-non-cs-to-backend",
        "headline": "From non-CS graduate to backend developer",
        "hook": "Consistent API projects and mock interviews helped Mohammed replace pedigree anxiety with demonstrable skill.",
        "track": "Full Stack",
        "background": "Non-CS background",
        "outcome_type": "First job",
        "program_label": "Full Stack Advanced",
        "before_title": "Mechanical engineering graduate",
        "after_title": "Backend developer",
        "company_name": "Bengaluru product company",
        "salary_before_lpa": None,
        "salary_after_lpa": "6.00",
        "salary_jump_percent": 0,
        "time_to_hire_months": 6,
        "quote": "Once I could defend my database and API choices, interviews stopped feeling like a test of my degree.",
        "advice": "Your degree becomes less important when your work is specific. Build something with users, constraints, and trade-offs you can defend.",
        "is_featured": False,
        "display_order": 5,
    },
    {
        "student_name": "Priya Shah",
        "slug": "priya-qa-to-ai-engineering",
        "headline": "From QA engineer to applied AI engineer",
        "hook": "Priya used her quality mindset to specialise in evaluation-heavy AI product work.",
        "track": "AI",
        "background": "Working professional",
        "outcome_type": "Salary growth",
        "program_label": "AI Engineer Track",
        "before_title": "QA engineer",
        "after_title": "Applied AI engineer",
        "company_name": "Enterprise AI studio",
        "salary_before_lpa": "6.50",
        "salary_after_lpa": "10.90",
        "salary_jump_percent": 68,
        "time_to_hire_months": 5,
        "quote": "Evaluation became my advantage. I already knew how to ask what could fail; now I could build the system too.",
        "advice": "Use your existing strengths as the bridge into a new specialism. AI teams need evaluation, product thinking, and reliability—not only model knowledge.",
        "is_featured": False,
        "display_order": 6,
    },
    {
        "student_name": "Arjun Das",
        "slug": "arjun-fresher-to-security-analyst",
        "headline": "From computer science fresher to security analyst",
        "hook": "Threat models and remediation reports gave Arjun stronger interview evidence than certificates alone.",
        "track": "Cyber Security",
        "background": "Fresher",
        "outcome_type": "First job",
        "program_label": "Secure Web Development",
        "before_title": "Computer science graduate",
        "after_title": "Junior security analyst",
        "company_name": "Security consulting firm",
        "salary_before_lpa": None,
        "salary_after_lpa": "5.80",
        "salary_jump_percent": 0,
        "time_to_hire_months": 4,
        "quote": "Writing remediation reports taught me to communicate risk, which became the centre of my best interview answers.",
        "advice": "Security is not a collection of scary terms. Practise finding, explaining, and fixing one concrete risk at a time.",
        "is_featured": False,
        "display_order": 7,
    },
    {
        "student_name": "Kavya Iyer",
        "slug": "kavya-customer-success-to-product-analytics",
        "headline": "From customer success to product analyst",
        "hook": "Kavya turned years of customer intuition into measurable product analysis and a stronger internal career move.",
        "track": "Data Science",
        "background": "Working professional",
        "outcome_type": "New role",
        "program_label": "Data Analytics Track",
        "before_title": "Customer success specialist",
        "after_title": "Product analyst",
        "company_name": "Consumer technology company",
        "salary_before_lpa": "5.80",
        "salary_after_lpa": "8.50",
        "salary_jump_percent": 47,
        "time_to_hire_months": 3,
        "quote": "I already understood customer pain. The programme taught me how to test that intuition with data.",
        "advice": "Start with questions from a domain you understand. Technical confidence grows faster when the business problem is already familiar.",
        "is_featured": False,
        "display_order": 8,
    },
]


def story_details(story):
    return {
        "before_description": f"{story['student_name']} began as a {story['before_title'].lower()}, with useful experience but no clear bridge into the target role.",
        "after_description": f"After building assessed work and practising how to explain it, {story['student_name']} moved into a {story['after_title'].lower()} role at {story['company_name']}.",
        "journey": [
            {"phase": "Foundation", "title": "Built the core vocabulary", "description": "Closed knowledge gaps through focused lessons and deliberate practice."},
            {"phase": "Application", "title": "Turned lessons into projects", "description": "Used mentor reviews to improve technical decisions and communication."},
            {"phase": "Career", "title": "Converted proof into interviews", "description": "Refined the portfolio, practised interviews, and targeted suitable roles."},
        ],
        "challenges": [
            "Balancing consistent study with existing work or personal commitments",
            "Moving beyond tutorial familiarity into independent problem solving",
            "Explaining a non-linear background confidently in interviews",
        ],
        "projects": [
            {"title": f"{story['track']} capstone", "description": "An end-to-end project reviewed against a practical skills rubric.", "skills": ["Planning", "Implementation", "Review"]},
            {"title": "Industry case study", "description": "A constrained problem requiring clear trade-offs and a documented outcome.", "skills": ["Analysis", "Communication", "Iteration"]},
        ],
        "outcomes": [
            {"label": "Role", "value": story["after_title"]},
            {"label": "Company", "value": story["company_name"]},
            {"label": "Time to hire", "value": f"{story['time_to_hire_months']} months"},
            {"label": "Salary growth", "value": f"{story['salary_jump_percent']}%" if story["salary_jump_percent"] else "First role"},
        ],
    }


class Command(BaseCommand):
    help = "Create or update representative public success-story records."

    def handle(self, *args, **options):
        for story in STORIES:
            slug = story["slug"]
            defaults = {key: value for key, value in story.items() if key != "slug"}
            defaults.update(story_details(story))
            defaults.update(status="published", is_placed=True)
            SuccessStory.objects.update_or_create(slug=slug, defaults=defaults)

        self.stdout.write(
            self.style.SUCCESS(f"Seeded {len(STORIES)} public success stories.")
        )
