# Generated by Django 5.2.8 on 2026-06-29 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyprofile',
            options={'ordering': ['display_order', '-is_featured', 'display_name']},
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='achievements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available for mentoring'), ('waitlist', 'Join waitlist'), ('unavailable', 'Currently unavailable')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='booking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='experience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='session_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='session_price_paise',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='sessions_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='students_mentored',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['is_public', 'is_featured', 'display_order'], name='faculty_fac_is_publ_6d00ae_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['availability'], name='faculty_fac_availab_861b6e_idx'),
        ),
    ]
