# Generated by Django 5.2.8 on 2026-06-29 15:03

import django.core.validators
import django.db.models.deletion
import reviews.models
from django.conf import settings
from django.db import migrations, models


def migrate_course_reviews_to_generic_targets(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")
    ContentType = apps.get_model("contenttypes", "ContentType")
    course_type = ContentType.objects.get(app_label="courses", model="course")

    for review in Review.objects.all().iterator():
        review.content_type_id = course_type.id
        review.object_id = review.course_id
        review.rating = min(max(review.rating or 1, 1), 5)
        review.comment = review.comment or ""
        review.status = "published"
        review.is_verified = True
        review.published_at = review.created_at
        review.save(
            update_fields=[
                "content_type",
                "object_id",
                "rating",
                "comment",
                "status",
                "is_verified",
                "published_at",
            ]
        )


def restore_legacy_course_targets(apps, schema_editor):
    Review = apps.get_model("reviews", "Review")

    for review in Review.objects.filter(
        content_type__app_label="courses",
        content_type__model="course",
    ).iterator():
        review.course_id = review.object_id
        review.save(update_fields=["course"])


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text_value', models.TextField(blank=True)),
                ('choice_values', models.JSONField(blank=True, default=list)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['question__display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_kind', models.CharField(choices=[('program', 'Program feedback'), ('course', 'Course feedback'), ('module', 'Module feedback'), ('lesson', 'Lesson feedback'), ('live_class', 'Live class feedback'), ('cohort', 'Cohort feedback'), ('general', 'General feedback')], db_index=True, max_length=20)),
                ('prompt', models.CharField(max_length=300)),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('response_type', models.CharField(choices=[('rating', '1–5 rating'), ('text', 'Free text'), ('single_choice', 'Single choice'), ('multiple_choice', 'Multiple choice'), ('boolean', 'Yes or no')], max_length=30)),
                ('dimension_key', models.CharField(blank=True, max_length=40)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['feedback_kind', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('program', 'Program feedback'), ('course', 'Course feedback'), ('module', 'Module feedback'), ('lesson', 'Lesson feedback'), ('live_class', 'Live class feedback'), ('cohort', 'Cohort feedback'), ('general', 'General feedback')], max_length=20)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('dimension_ratings', models.JSONField(blank=True, default=dict, validators=[reviews.models.validate_dimension_ratings])),
                ('comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('staff', 'Staff only'), ('instructors', 'Assigned instructors and staff'), ('admin', 'Administrators only')], default='staff', max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged'), ('archived', 'Archived')], db_index=True, default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-is_featured', '-helpful_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='public_reviews', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending moderation'), ('published', 'Published'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(
            migrate_course_reviews_to_generic_targets,
            restore_legacy_course_targets,
        ),
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='public_reviews', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='public_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['content_type', 'object_id'], name='reviews_rev_content_627d80_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'rating'], name='reviews_rev_status_11234f_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'is_featured'], name='reviews_rev_status_24c988_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', 'is_verified'], name='reviews_rev_status_a79f54_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackquestion',
            index=models.Index(fields=['feedback_kind', 'is_active', 'display_order'], name='reviews_fee_feedbac_617c8f_idx'),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='reviews.feedbackquestion'),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submissions', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedback_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reviews.feedbacksubmission'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['content_type', 'object_id'], name='reviews_fee_content_195109_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['kind', 'status'], name='reviews_fee_kind_f8642a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['student', 'created_at'], name='reviews_fee_student_85f585_idx'),
        ),
        migrations.AddConstraint(
            model_name='feedbacksubmission',
            constraint=models.UniqueConstraint(fields=('student', 'content_type', 'object_id', 'kind'), name='unique_student_feedback_per_target_kind'),
        ),
        migrations.AddConstraint(
            model_name='feedbackanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_feedback_answer_per_question'),
        ),
    ]
