# Generated by Django 5.2.8 on 2026-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('current_role', models.CharField(max_length=180)),
                ('company', models.CharField(blank=True, max_length=180)),
                ('expertise', models.JSONField(default=list)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('motivation', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('interview', 'Interview'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sales_instr_status_8e4e75_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnerEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=220)),
                ('contact_name', models.CharField(max_length=180)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('partnership_type', models.CharField(choices=[('institution', 'Institution Partner'), ('pro', 'PRO Partner'), ('placement', 'Placement Partner')], max_length=20)),
                ('website_url', models.URLField(blank=True)),
                ('organization_size', models.CharField(blank=True, max_length=80)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sales_partn_status_8b45bb_idx'), models.Index(fields=['partnership_type', 'created_at'], name='sales_partn_partner_10442c_idx')],
            },
        ),
    ]
