# Generated by Django 5.2.8 on 2026-06-30 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSupportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=24)),
                ('category', models.CharField(choices=[('admissions', 'Admissions'), ('program', 'Program or curriculum'), ('payment', 'Payment or refund'), ('placement', 'Placement support'), ('certificate', 'Certificate'), ('technical', 'Technical issue'), ('account', 'Account access'), ('other', 'Other')], max_length=24)),
                ('subject', models.CharField(max_length=220)),
                ('message', models.TextField()),
                ('source_path', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='tickets_pub_status_9cca6f_idx'), models.Index(fields=['category', 'created_at'], name='tickets_pub_categor_f9105d_idx')],
            },
        ),
    ]
