# Generated by Django 5.2.8 on 2026-06-30 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('public_content', '0002_publicdomain_roadmaptrack_alter_roadmapstep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('headline', models.CharField(max_length=255)),
                ('hook', models.CharField(max_length=320)),
                ('photo_url', models.URLField(blank=True)),
                ('track', models.CharField(db_index=True, max_length=120)),
                ('background', models.CharField(db_index=True, max_length=120)),
                ('outcome_type', models.CharField(db_index=True, max_length=120)),
                ('program_label', models.CharField(max_length=160)),
                ('before_title', models.CharField(max_length=180)),
                ('before_description', models.TextField(blank=True)),
                ('after_title', models.CharField(max_length=180)),
                ('after_description', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('salary_before_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('salary_after_lpa', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('salary_jump_percent', models.PositiveIntegerField(default=0)),
                ('time_to_hire_months', models.PositiveIntegerField(blank=True, null=True)),
                ('is_placed', models.BooleanField(db_index=True, default=True)),
                ('quote', models.TextField(blank=True)),
                ('journey', models.JSONField(blank=True, default=list)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('outcomes', models.JSONField(blank=True, default=list)),
                ('advice', models.TextField(blank=True)),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='success_stories', to='programs.learningprogram')),
            ],
            options={
                'verbose_name_plural': 'Success stories',
                'ordering': ['display_order', '-published_at', 'student_name'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='public_cont_status_65c343_idx'), models.Index(fields=['track', 'background', 'outcome_type'], name='public_cont_track_c3f89d_idx'), models.Index(fields=['slug'], name='public_cont_slug_489524_idx')],
            },
        ),
    ]
