# Generated by Django 5.2.8 on 2026-06-30 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certifications', '0001_initial'),
        ('courses', '0017_remove_course_faculty_remove_course_instructor_image_and_more'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('short_description', models.CharField(max_length=320)),
                ('description', models.TextField()),
                ('certification_type', models.CharField(choices=[('program', 'Program'), ('track', 'Track'), ('course', 'Course')], max_length=20)),
                ('domain', models.CharField(choices=[('full-stack', 'Full Stack'), ('data', 'Data'), ('ai', 'AI'), ('devops', 'DevOps'), ('security', 'Security')], max_length=30)),
                ('level', models.CharField(max_length=80)),
                ('duration', models.CharField(max_length=80)),
                ('skills', models.JSONField(default=list)),
                ('outcomes', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('assessment_methods', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_offerings', to='courses.course')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certification_offerings', to='programs.learningprogram')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='certificati_is_acti_019d6b_idx'), models.Index(fields=['certification_type', 'domain'], name='certificati_certifi_56bcfd_idx')],
            },
        ),
    ]
